[package]
name = "make_quaternion"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.19", features = ["derive"] }
libm = "0.2.5"
configparser = "3.0.1"
hdf5 = "0.8.1"
